Updated the util file & started TC145
raffiGocer/TeamCollab pull request #2
Opened 2023-01-02 02:45 UTC by raffiGocer

2023-01-02 18:09 UTC, jule4ka881 requested changes
static is missing

2023-01-05 03:44 UTC, AnastasiiaDiab requested changes
Please add Hello World

2023-01-05 03:50 UTC, AnastasiiaDiab approved these changes
Excellent

2023-01-05 03:53 UTC, jule4ka881 reviewed
great

2023-01-05 03:54 UTC, jule4ka881 approved these changes

2023-01-05 03:54 UTC, merged